### ISSUE TITLE
Was `apachebeam`  intended to use different mqtt topic?

### ISSUE THREAD

**Issue by tedli** [kubeedge/examples#10]
At publisher side, message published with topic "test"
https://github.com/kubeedge/examples/blob/d813b7bd33d20d4f40fb9c8e5bc75c79e0a89627/KE-Apache-Beam-Analysis/MQTT_Publisher/testmachine.go#L77

Meanwhile, at the subscriber side, it consumed message with topic "alert"
https://github.com/kubeedge/examples/blob/d813b7bd33d20d4f40fb9c8e5bc75c79e0a89627/KE-Apache-Beam-Analysis/MQTT_Subscriber/testmachinealert.go#L35

Program runs, but without any output, and occasionally publisher panics at
https://github.com/kubeedge/examples/blob/d813b7bd33d20d4f40fb9c8e5bc75c79e0a89627/KE-Apache-Beam-Analysis/MQTT_Publisher/testmachine.go#L75-L83

The error is
https://github.com/yosssi/gmq/blob/b221999646da8ea48ff0796c2b0191aa510d062e/mqtt/client/client.go#L232-L242

**Comment by m1093782566** [comment]
cc @SupriyaSupu Please take a look.

**Comment by sids-b** [comment]
@tedli , the testmachine publishes data on the test topic. Apache bean analyzes the data and if the average of a window is above threshold(i guess it is above 90) , the apache bean pipeline publishes an alert message on alert topic which is subscribed by testmachinealert.go for outputting.

**Comment by tedli** [comment]
> @tedli , the testmachine publishes data on the test topic. Apache bean subscribes and analyzes the data from test topic and if the average of a window is above threshold(i guess it is above 90) , the apache bean pipeline publishes an alert message on alert topic which is subscribed by testmachinealert.go for outputting.

Thanks for reply, I got it.
