### ISSUE TITLE
kubeedge-counter-demo no working on kubeedge 1.6.2

### ISSUE THREAD

**Issue by punkmonday** [kubeedge/examples#102]
kubectl create -f kubeedge-counter-model.yaml
error: unable to recognize "kubeedge-counter-model.yaml": no matches for kind "DeviceModel" in version "devices.kubeedge.io/v1alpha2"

**Comment by fisherxu** [comment]
You need to check whether the crds `devicemodels.devices.kubeedge.io` and `devices.devices.kubeedge.io` have been created in the K8s master.

```
kubectl get crds
```

**Comment by punkmonday** [comment]
> You need to check whether the crds `devicemodels.devices.kubeedge.io` and `devices.devices.kubeedge.io` have been created in the K8s master.
> 
> ```
> kubectl get crds
> ```


2021/08/20 07:24:00 Failed to patch device status &{{[{status {ON map[timestamp:1629 type:string]} {1 map[timestamp:1629 type:string]}}]}} of device counter in namespace default
 error:the server could not find the requested resource (patch devices.devices.kubeedge.io counter)

**Comment by punkmonday** [comment]
when i change version v1alpha1 to v1alpha2
```
root@localhost ~/g/s/e/k/crds (master)# kubectl create -f kubeedge-counter-model.yaml
error: unable to recognize "kubeedge-counter-model.yaml": no matches for kind "DeviceModel" in version "devices.kubeedge.io/v1alpha2"

```
so i changed to v1alpha1 it is work, but docker logs error:

```
error:the server could not find the requested resource (patch devices.devices.kubeedge.io counter)
```

**Comment by punkmonday** [comment]
i got it , it works , i delete the v1alpha1 version and create v1alpha2
```
kubectl create -f https://github.com/kubeedge/kubeedge/blob/master/build/crds/devices/devices_v1alpha2_devicemodel.yaml
kubectl create -f https://github.com/kubeedge/kubeedge/blob/master/build/crds/devices/devices_v1alpha2_device.yaml
```

**Comment by Aix6** [comment]
> 



> i got it , it works , i delete the v1alpha1 version and create v1alpha2
> 
> ```
> kubectl create -f https://github.com/kubeedge/kubeedge/blob/master/build/crds/devices/devices_v1alpha2_devicemodel.yaml
> kubectl create -f https://github.com/kubeedge/kubeedge/blob/master/build/crds/devices/devices_v1alpha2_device.yaml
> ```

请问是参考这两个来修改 example 里的吗？不是直接使用这两个连接里的配置文件创建吧？我看这里面的配置比 example 里多太多了
