### ISSUE TITLE
Should I run a sub to get the output message from Apache Beam example?

### ISSUE THREAD

**Issue by m1093782566** [kubeedge/examples#15]
Reported by cong wang,

Hi,I have tried the KE-Apache-Beam-Analysis example on githuh, after run ./testmachine.what message could I get?should I run a sub to get the output message?

cc @sids-b

**Comment by m1093782566** [comment]
@SupriyaSupu Please take a look when you got the chance.

**Comment by sids-b** [comment]
there is a subscribe file for getting alerts whenever the temperature crosses threshold(i remember it was 90, not sure though. we can check from the output of running this file). 
https://github.com/kubeedge/examples/blob/master/KE-Apache-Beam-Analysis/MQTT_Subscriber/testmachinealert.go

**Comment by congfairy** [comment]
@m1093782566 @sids-b thanks a looooot.I have found the right way to catch the result.
