### ISSUE TITLE
couldn't find suitable file to run  about security-demo

### ISSUE THREAD

**Issue by congfairy** [kubeedge/examples#16]
Hi, I have tried to run this example .But what do you mean by 
![image](https://user-images.githubusercontent.com/13255322/56415808-6c7f4100-62c1-11e9-812c-e7fb5af02d13.png)
since I could find nothing to run  under /app-binaries/cloud/ folder
![image](https://user-images.githubusercontent.com/13255322/56415844-8f115a00-62c1-11e9-864a-e15a35626386.png).
could anyone help me to explain clearly how to test device application?thanks a lot.

**Comment by m1093782566** [comment]
cc @trilokgm

**Comment by trilokgm** [comment]
@congfairy , can you run build-release package? build-release script needs to be executed from the clone directory. The scripts builds all required applications and copies to release folder. Later this folder should be copied to /opt/ and renamed to /opt/spire/ . I will update the same in readme. Let us know if any more issues are seen.

**Comment by daixiang0** [comment]
Please try the latest example to confirm this issue exists or not, it works at my env, thanks :)

If it still exists, please reopen it!

/close
