### ISSUE TITLE
Bug with the raspberry pi example

### ISSUE THREAD

**Issue by gilles537** [kubeedge/examples#25]
The pod seems to be running fine and seems to be detecting changes in the led value after PR: https://github.com/kubeedge/examples/pull/24. But now there is a problem with reading the gpio-number from the configmap. After running the code ```glog.Info(pinNumber)``` right before the call ```lightdriver.TurnOff(pinNumber)``` i read the output 0. So the light isn't turning on.

**Comment by sujithsimon22** [comment]
Nice catch @gilles537
