### ISSUE TITLE
Desired property replicates for each field in CRD

### ISSUE THREAD

**Issue by mg9** [kubeedge/examples#28]
Hello,

I was trying to change the led-mapper example to integrate device twins with my another application. 
When I try to change multiple expected values in instance.yaml of device, the updated document is formed with only last desired value for all properties. Does instance CRD support only one desired field ? 

What I mean,

My instance.yaml:

apiVersion: devices.kubeedge.io/v1alpha1
kind: Device
metadata:
  name: my-app-instance-01
  labels:
    description: MYApp
    model: my-app
spec:
  deviceModelRef:
    name: my-app
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: ''
        operator: In
        values:
        - myedge01          #pls give your edge node name
status:
  twins:
    - propertyName: prop1
      desired:
        metadata:
          type: string
        value: 'value1'
    - propertyName: prop2
      desired:
        metadata:
          type: string
        value: 'value2'  
    - propertyName: prop3
      desired:
        metadata:
          type: string
        value: 'value3'  

The updated document published result in $hw/events.../twin/update/delta:
  "delta": {
    "prop1": "value3",
    "prop2": "value3",
    "prop3": "value3"
  }

Thank you very much...

**Comment by sujithsimon22** [comment]
Hi @mg9 are u testing with the latest code ? Is this issue https://github.com/kubeedge/kubeedge/issues/662 similar to what u are facing?

**Comment by mg9** [comment]
Yes sorry latest code fixed my problem, thank you!
