### ISSUE TITLE
温度传感器通过mqtt无法正常获取。

### ISSUE THREAD

**Issue by daqiangzi** [kubeedge/examples#36]
kubeedge-v1.1.0，温度传感器mqqt发送，不成功，请确认原因.
步骤1：
kubectl apply -f devicemodel.yaml
==========================================================
apiVersion: devices.kubeedge.io/v1alpha1
kind: Device
metadata:
  name: temperature
  labels:
    description: 'temperature'
    manufacturer: 'test'
spec:
  deviceModelRef:
    name: temperature-model
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: ''
            operator: In
            values:
              - node-test001  # 节点名称
status:
  twins:
    - propertyName: temperature-status
      desired:
        metadata:
          type: string
        value: ''
步骤2：
kubectl apply -f device.yaml
==========================================================
apiVersion: devices.kubeedge.io/v1alpha1
kind: DeviceModel
metadata:
  name: temperature-model
  namespace: default
spec:
  properties:
    - name: temperature-status
      description: Temperature collected from the edge device
      type:
        string:
          accessMode: ReadOnly
          defaultValue: ''		

步骤3：修改并启动edgecore应用
修改edge.yaml
============================================================
mqtt:
    server: tcp://127.0.0.1:1883 # external mqtt broker url.
    internal-server: tcp://127.0.0.1:1884 # internal mqtt broker url.
    mode: 2 # 0: internal mqtt broker enable only. 1: internal and external mqtt broker enable. 2: external mqtt broker enable only.
    qos: 0 # 0: QOSAtMostOnce, 1: QOSAtLeastOnce, 2: QOSExactlyOnce.
    retain: false # if the flag set true, server will store the message and can be delivered to future subscribers.
    session-queue-size: 100 # A size of how many sessions will be handled. default to 100.

edgehub:

步骤4：发送数据：		
订阅topic：
mosquitto_sub -t "$hw/events/device/temperature/twin/update"

发送数据：
mosquitto_pub -h localhost -p 1883 -t "$hw/events/device/temperature/twin/update" -m "{"event_id":"","timestamp":1578400875814,"twin":{"temperature-status":{"last":{"actual":{"value":"27C","metadata":{"timestamp":1578400873775}},"optional":false,"metadata":{"type":"string"}},"current":{"actual":{"value":"27C","metadata":{"timestamp":1578400875814}},"optional":false,"metadata":{"type":"string"}}}}}"

步骤5：kubectl get device temperature -oyaml -w
一直无法正常获取到温度数据，请确认问题。

**Comment by fisherxu** [comment]
看下edgecore的日志，是否收到了publish到mosquitto的消息，如果edgecore收到了，再看一下cloudcore是否收到了 ：） @daqiangzi

**Comment by daqiangzi** [comment]
edgecore日志中没有收到mosquitto的消息，请确认一下上面修改是否正确。

**Comment by daqiangzi** [comment]
> 看下edgecore的日志，是否收到了publish到mosquitto的消息，如果edgecore收到了，再看一下cloudcore是否收到了 ：） @daqiangzi

edgecore日志中没有收到

**Comment by daqiangzi** [comment]
@fisherxu 
写了一个应用程序，模拟往mqqt里发送数据，就正常获取到了。谢谢。

**Comment by shawn-robusoft** [comment]
> @fisherxu 写了一个应用程序，模拟往mqqt里发送数据，就正常获取到了。谢谢。

怎么写的，我现在部署了一个 KubeEdge，也想通过 发送MQTT消息的模拟程序，来看看是否能修改 get device获取到的数字孪生属性字段的值。目前还没成功。
