### ISSUE TITLE
/opt/kubeedge/deviceProfile.json: no such file or directory

### ISSUE THREAD

**Issue by wangwei5732** [kubeedge/examples#37]
when i run light_driver.go,by `go run light_mapper.go`,Error:
`E0116 19:03:18.082379    8173 light_mapper.go:121] Error while reading from config map Error while reading from config map open /opt/kubeedge/deviceProfile.json: no such file or directory
exit status 1`

**Comment by latelee** [comment]
I got the same issue too.

**Comment by fisherxu** [comment]
when we create the devicemodel, the devicecontroller in cloudcore will create a configmap which will be used in mapper(pod) in edge node. Please check whether devicecontroller has create the configmap.
