### ISSUE TITLE
如何能在容器中访问接入的设备？

### ISSUE THREAD

**Issue by wangwei5732** [kubeedge/examples#38]
请问如何能够在容器中访问挂载在树莓派上的设备。

**Comment by fisherxu** [comment]
容器里可以访问到类似于gpio的，具体是什么样的设备呢？:) @wangwei5732

**Comment by wangwei5732** [comment]
我按照led-raspberrypi，的步骤操作，打的镜像运行以后提示找不到设备，报错。我想问下还需要额外的操作或者配置吗？

**Comment by latelee** [comment]
@wangwei5732，可以单独测试镜像运行情况，即脱离kueedge环境。我记得要进行设备的映射，还要为容器提供特权。

**Comment by happyhq** [comment]
> 请问如何能够在容器中访问挂载在树莓派上的设备。

能够具体描述一下场景么？

**Comment by daixiang0** [comment]
Please try the latest example to confirm this issue exists or not, it works at my env, thanks :)

If it still exists, please reopen it!

/close
