### ISSUE TITLE
Is the arch on the docker image for the temperature demo correct on amd64?

### ISSUE THREAD

**Issue by keisuke-maesako** [kubeedge/examples#42]
I want to run a temperature demo.
I built and pushed from dockerfile according to the readme.
Checking dockerhub, the OS / ARCH column is linux / amd64.
I think this doesn't work with Raspberry Pi, but is something wrong?

**Comment by daixiang0** [comment]
Please see the latest README, there is an image for arm and one for amd64.

/close
