### ISSUE TITLE
Use of Opensource Cloud for apache bean demo.

### ISSUE THREAD

**Issue by sids-b** [kubeedge/examples#5]
Currently apache beam demo uses IEF for application deployment as when the demo was uploaded cloud was not available for kubeedge. Since cloud is available from v0.2 of kubeedge, dependency of IEF for deploying applications no longer exists.

Apache Beam demo needs to be changed to use opensource cloud.

**Comment by sids-b** [comment]
@SupriyaSupu , Please help with this.

cc @CindyXing @m1093782566 @rohitsardesai83

**Comment by SupriyaSupu** [comment]
I am working on this.
