### ISSUE TITLE
Build main.go failure

### ISSUE THREAD

**Issue by yzhao66** [kubeedge/examples#51]
when i run this example 

![image](https://user-images.githubusercontent.com/44268973/87017526-ab6d1f80-c202-11ea-9f85-ab054fa338f8.png)

**Comment by gitlijian** [comment]
需要用docker编译：
我参考的这篇博客，希望对你有帮助

**Comment by yzhao66** [comment]
> 需要用docker编译：
> 我参考的这篇博客https://blog.csdn.net/weixin_44738411/article/details/107049358
> 希望对你有帮助！

有用过kubeedge-traffic-light吗

**Comment by gitlijian** [comment]
没有，我还在用温度这个demo时遇到了些问题。

**Comment by swartz-k** [comment]
u need covert this to go mod or refer pr

**Comment by daixiang0** [comment]
Now it has moved to Go Module. :)

/close
