### ISSUE TITLE
edge ：connect error: Not Authorized

### ISSUE THREAD

**Issue by gitlijian** [kubeedge/examples#53]
edge side shows connect error: Not Authorized
![image](https://user-images.githubusercontent.com/15320599/87139632-e50d5b80-c2d2-11ea-8534-0269ba41320e.png)
cloud side shows Works fine
![image](https://user-images.githubusercontent.com/15320599/87139993-5cdb8600-c2d3-11ea-9ba7-06ccb0f1ee43.png)
![Uploading image.png…]()
anyone can help me address the problem?

**Comment by daixiang0** [comment]
Please try the latest example to confirm this issue exists or not, thanks :)

**Comment by daixiang0** [comment]
It has been fixed, please try the latest example with latest KubeEdge.

/close
