### ISSUE TITLE
Upgrade all examples to go module

### ISSUE THREAD

**Issue by YoshieraHuang** [kubeedge/examples#54]
I am new to kubeedge and I see many examples are governed by dep. Dep is already deprecated and go module does well. Need some help?

**Comment by fisherxu** [comment]
@YoshieraHuang  Sure, and now every example have one vendor, we can use one vendor for all the examples.

**Comment by zhangweidongyyl** [comment]
You can use it go.mod Manage the project and package it. That's what I do

**Comment by YoshieraHuang** [comment]
I meet a problem. modules `kubeedge/beehive` and `kubeedge/viaduct` with latest version are now replaced as inset modules in `kubeedge/kubeedge` and cannot be easily accessed in this repository. Although we can `go get` this two modules with previous version, the previous version is not compatible with 1.3.1. The compatibility cause this error:
```
# github.com/kubeedge/kubeedge/edge/pkg/devicetwin/dtclient
../../go/pkg/mod/github.com/kubeedge/kubeedge@v1.3.1/edge/pkg/devicetwin/dtclient/sql.go:23:12: module.Enable undefined (type core.Module has no field or method Enable)
```
when I build `kubeedge-traffic-light`. Will beehive and viaduct be seperated from main repository?

**Comment by daixiang0** [comment]
Now it has been fixed.

/close
