### ISSUE TITLE
kubeedge-pi-counter can not connect to edge?

### ISSUE THREAD

**Issue by zhangweidongyyl** [kubeedge/examples#55]
kubeedge-pi-counter can not connect to edge ,the detail msg is 
Error from server: Get https://XXXX:10350/containerLogs/default/kubeedge-pi-counter-86576974c8-9mxjm/kubeedge-pi-counter?follow=true: dial tcp XXXX:10350: connect: connection refused
kubeedge has wechat group or other contact information ，The document is poorly written ?

**Comment by zhangweidongyyl** [comment]
someone knows how to resolve this question

**Comment by zhanglt** [comment]
[root@master crds]# kubectl  logs -f kubeedge-pi-counter-68c86dc747-lrgdq 
Error from server: Get "https://10.0.0.62:10350/containerLogs/default/kubeedge-pi-counter-68c86dc747-lrgdq/kubeedge-pi-counter?follow=true": dial tcp 10.0.0.62:10350: connect: connection refused
------edge node-------------
[root@edge ~]# netstat -luntp  |grep 10350
tcp        0      0 127.0.0.1:10350         0.0.0.0:*               LISTEN      9164/edgecore

**Comment by daixiang0** [comment]
Seems you do not enable LOGS feature on the edge, you can refer to this [doc](https://github.com/kubeedge/kubeedge/blob/release-1.5/docs/setup/keadm.md#enable-kubectl-logs-feature)

/close
