### ISSUE TITLE
kubeedge-counter-demo cannot run on kubeedge-1.4.0

### ISSUE THREAD

**Issue by zhangweidongyyl** [kubeedge/examples#64]
it has no error on log,bug when i click on ,my edge side can not accept any message, it can not trigger code.  is a question  ,maybe a bug

token := cli.Subscribe(topic+"/document", 0, func(client mqtt.Client, msg mqtt.Message) {
		fmt.Println("enter get msg",msg)
		Update := &types.DeviceTwinDocument{}
		err := json.Unmarshal(msg.Payload(), Update)
		if err != nil {
			fmt.Printf("Unmarshal error: %v\n", err)
		}

		cmd := *Update.Twin["status"].CurrentState.Expected.Value

		if cmd == "ON" && cmd != current_status {
			ctr.TurnOn()
			fmt.Printf("turn on counter.\n")
		}

		if cmd == "OFF" && cmd != current_status {
			ctr.TurnOff()
			fmt.Printf("turn off counter.\n")
		}

		current_status = cmd
	})

**Comment by swartz-k** [comment]
i use this demo，get errors below
1. in browser console，load jquery.js failed；i save it to local
2. x509 to get self provide tls；i add `rest.TLSClientConfig{Insecure: true}`
3. KubeMaster、Kubeconfig not validate；create clusterole & serviceaccount and use `rest.InClusterConfig`
4. （maybe not important）change restful http client to dynamic client，and use `schema.GroupVersionResource`

**Comment by daixiang0** [comment]
Please try the latest example to confirm this issue exists or not, thanks :)

**Comment by daixiang0** [comment]
Please try the latest example to confirm this issue exists or not, it works at my env, thanks :)

If it still exists, please reopen it!

/close
