### ISSUE TITLE
KubeEdge Counter Demo is not working properly

### ISSUE THREAD

**Issue by zhangyang1997** [kubeedge/examples#65]
**What happened**:
KubeEdge Counter Demo is not working properly
**What you expected to happen**:
use [kubectl get pods -o wide] can get ke-edge1's IP and use [docker logs -f counter-container-id] can get count value.

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`): v1.4.0
**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz
- OS (e.g. `cat /etc/os-release`):centos8
- Kernel (e.g. `uname -a`):Linux ke-cloud 4.18.0-193.el8.x86_64 #1 SMP Fri May 8 10:59:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Go version (e.g. `go version`): go version go1.14.4 linux/amd64
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):v1.4.0
- Hardware configuration (e.g. `lscpu`):Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz
- OS (e.g. `cat /etc/os-release`):centos8
- Kernel (e.g. `uname -a`):Linux ke-edge1 4.18.0-193.el8.x86_64 #1 SMP Fri May 8 10:59:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Go version (e.g. `go version`): go version go1.14.4 linux/amd64
- Others:

![p1](https://user-images.githubusercontent.com/22254602/93102699-4f30eb00-f6de-11ea-9941-bbede2190d44.png)
![p2](https://user-images.githubusercontent.com/22254602/93102713-51934500-f6de-11ea-9ebe-851f6fbd5c9a.png)
![p3](https://user-images.githubusercontent.com/22254602/93102719-52c47200-f6de-11ea-8299-02a97f3c4755.png)
![p4](https://user-images.githubusercontent.com/22254602/93102725-548e3580-f6de-11ea-8840-6c5ebd5d1555.png)
![p5](https://user-images.githubusercontent.com/22254602/93110244-a5565c00-f6e7-11ea-9700-3f9a2d55288e.png)

**Comment by yiye93** [comment]
请问怎么解决的，我遇到一样的问题了

**Comment by bluntWu** [comment]
edit /etc/kubernetes/manifests/kube-apiserver.yaml
 --insecuret-port=8080
 --insecure-bind-address=0.0.0.0
restart

**Comment by swartz-k** [comment]
the quickesty way, i think； file: `examples/kubeedge-counter-demo/web-controller-app/utils/kubeclient.go` should be edit like this

```
// replace this with the K8s Master IP
var KubeMaster = "https://192.68.105.207:6443"
var Kubeconfig = "/static/admin.conf"
```

and copy admin.conf to your container；file`examples/kubeedge-counter-demo/web-controller-app/Dockerfile` add line 
```
COPY admin.conf /static 
```

the better way is get permission by clusterrole && clusterrolebinding && serviceaccount，i think this demo has a better way to update CR，if i will solve those problems，i will share it

**Comment by DapengLan** [comment]
> edit /etc/kubernetes/manifests/kube-apiserver.yaml
> --insecuret-port=8080
> --insecure-bind-address=0.0.0.0
> restart

I got the issue that the port is in use by the Kube-api. any suggestions? thanks

2020/12/11 13:22:23 Get kubeConfig successfully
2020/12/11 13:22:23 Get crdClient successfully
2020/12/11 13:22:24.001 [I]  http server Running on http://:8089
2020/12/11 13:22:24.001 [C]  ListenAndServe:  listen tcp :8089: bind: address already in use

**Comment by swartz-k** [comment]
> > edit /etc/kubernetes/manifests/kube-apiserver.yaml
> > --insecuret-port=8080
> > --insecure-bind-address=0.0.0.0
> > restart
> 
> I got the issue that the port is in use by the Kube-api. any suggestions? thanks
> 
> 2020/12/11 13:22:23 Get kubeConfig successfully
> 2020/12/11 13:22:23 Get crdClient successfully
> 2020/12/11 13:22:24.001 [I] http server Running on http://:8089
> 2020/12/11 13:22:24.001 [C] ListenAndServe: listen tcp :8089: bind: address already in use

maybe you should check deployment，`hostNetwork: true` i delete it and didn`t get error

**Comment by daixiang0** [comment]
Please try the latest example to confirm this issue exists or not, thanks :)

**Comment by daixiang0** [comment]
Please try the latest example to confirm this issue exists or not, it works at my env, thanks :)

If it still exists, please reopen it!

/close
