### ISSUE TITLE
【counter】Failed to patch device status

### ISSUE THREAD

**Issue by zhangyang1997** [kubeedge/examples#66]
when I click on button，get a error
docker logs f127dbffa472(k8s_kubeedge-counter-app_kubeedge-counter-app)

![p5](https://user-images.githubusercontent.com/22254602/93170948-c310d900-f75a-11ea-9e3a-466a54f71b4f.png)

**Comment by zhangyang1997** [comment]
![p6](https://user-images.githubusercontent.com/22254602/93332925-2a12b880-f855-11ea-87c4-8f119213e309.png)

**Comment by donggangcj** [comment]
是device版本导致的，请问这个问题什么时候能修复？

**Comment by robertzhouxh** [comment]
kubeadm: 1.18.3
kubernetes: 1.18.3
CNI: weave
kubeedge: local deployment with master branch, 

test: github.com/kubeedge/examples/kubeedge-counter-demo

     root@master-1:~# kubectl get pods -n kube-system
    NAME                               READY   STATUS    RESTARTS   AGE
    coredns-546565776c-8c2rn           1/1     Running   0          4h22m
    coredns-546565776c-sgscr           1/1     Running   0          4h22m
    etcd-master-1                      1/1     Running   0          4h22m
    kube-apiserver-master-1            1/1     Running   0          105m
    kube-controller-manager-master-1   1/1     Running   3          4h22m
    kube-proxy-657vl                   1/1     Running   0          3h25m
    kube-proxy-r7fng                   1/1     Running   0          4h22m
    kube-scheduler-master-1            1/1     Running   2          4h22m
    weave-net-p27xr                    2/2     Running   0          4h17m
    weave-net-zgnfg                    0/2     Error     48         3h25m


    root@master-1:~# kubectl get node
    NAME       STATUS   ROLES        AGE     VERSION
    edge-1     Ready    agent,edge   3h24m   v1.18.6-kubeedge-v1.4.0-beta.0.192+e0aa3658c43bc9
    master-1   Ready    master       4h22m   v1.18.3

    root@master-1:# kubectl get pod
    NAME                                    READY   STATUS    RESTARTS   AGE
    kubeedge-counter-app-6984dcb4dd-4gn7v   1/1     Running   0          102m
    kubeedge-pi-counter-784d57c5d4-4s2xs    1/1     Running   0          101m


    root@master-1:~# kubectl logs -f kubeedge-counter-app-6984dcb4dd-4gn7v -n default

    2020/10/12 03:31:26 Failed to patch device status &{{[{status {ON map[timestamp:1602 type:string]} {0 map[timestamp:1602 type:string]}}]}} of device counter in namespace default

**Comment by zhangyang1997** [comment]
Has anyone solved this problem？Is this project now unmaintained?

**Comment by yiye93** [comment]
I also encountered this problem，has anyone solved this problem？

**Comment by johnp41** [comment]
Did anyone solved this  ?

**Comment by swartz-k** [comment]
while running counter demo，i solved `KubeMaster`、`Kubeconfig` problem by change code to fit my cluster，and then i got failed
```2020/12/11 09:50:44 Failed to patch device status &{{[{status {ON map[timestamp:1607 type:string]} {0 map[timestamp:1607 type:string]}}]}} of device counter in namespace default
 error:Patch "https://10.122.105.207:6443/apis/devices.kubeedge.io/v1alpha1/namespaces/default/devices/counter": x509: certificate signed by unknown authority```
maybe i am a long way to meet the same error，but i think we need to change the source code or if possible make a pr？

**Comment by daixiang0** [comment]
Please try the latest example to confirm this issue exists or not, thanks :)

**Comment by daixiang0** [comment]
Please try the latest example to confirm this issue exists or not, it works at my env, thanks :)

If it still exists, please reopen it!

/close
