### ISSUE TITLE
kubeedge-temperature-demo can not get data to cloud

### ISSUE THREAD

**Issue by wzq12345678** [kubeedge/examples#70]
I can subscribe to data from the side theme ($HW / events / device / + / Twin / update), but I can't display it in the cloud

**Comment by daixiang0** [comment]
Please try the latest example to confirm this issue exists or not, thanks :)

**Comment by daixiang0** [comment]
Please try the latest example to confirm this issue exists or not, it works at my env, thanks :)

If it still exists, please reopen it!

/close
