### ISSUE TITLE
Run RPI Temperature demo error, can not create the device model

### ISSUE THREAD

**Issue by mxtsuper** [kubeedge/examples#71]
Hello,
I am trying the RPI temperature demo. 
When applying the device model (devicemodel.yaml), I got some errors. 
Please need some supports on this error.
Thanks 

 error: unable to recognize "devicemodel.yaml": no matches for kind "DeviceModel" in version "devices.kubeedge.io/v1alpha2"

I am using the kubeedge 1.4.0, kubernetes v1.17.8

**Comment by Sullivan12138** [comment]
Hi, I've met the same error too. How did you fix this?
