### ISSUE TITLE
i can get temperature but i can not get humidity  when i definition humidity-status propertyName in devicemodel.yaml and device.yaml

### ISSUE THREAD

**Issue by wzq12345678** [kubeedge/examples#72]

**Comment by wzq12345678** [comment]
i also push humidity to mqtt in edgenode ,so  how i can solve the problem about this

**Comment by daixiang0** [comment]
cc @luogangyi

**Comment by daixiang0** [comment]
Please try the latest example to confirm this issue exists or not, thanks :)

**Comment by daixiang0** [comment]
Please try the latest example to confirm this issue exists or not, it works at my env, thanks :)

If it still exists, please reopen it!

/close
