### ISSUE TITLE
kubeedge-counter-demo  Click counter is error

### ISSUE THREAD

**Issue by beyondyinjl2** [kubeedge/examples#88]
docker logs -f 708687d34153(kubeedge-counter-app Container id)
The error is as follows:
2021/01/08 02:14:43 ControlTrack: ON
2021/01/08 02:14:43 Failed to patch device status &{{[{status {ON map[timestamp:1610 type:string]} {0 map[timestamp:1610 type:string]}}]}} of device counter in namespace default 
 error:the server could not find the requested resource (patch devices.devices.kubeedge.io counter)

environment:
kubectl get node
NAME         STATUS   ROLES        AGE     VERSION
k8s-master   Ready    master       3h21m   v1.19.2
k8s-node-1   Ready    agent,edge   3h4m    v1.19.3-kubeedge-v1.5.0

kubectl get pods -o wide
NAME                                   READY   STATUS    RESTARTS   AGE    IP              NODE         NOMINATED NODE   READINESS GATES
kubeedge-counter-app-b685d8f99-x7z69   1/1     Running   2          3h3m   172.16.72.143   k8s-master   <none>           <none>
kubeedge-pi-counter-68c86dc747-9xlks   1/1     Running   3          3h2m   172.16.72.142   k8s-node-1   <none>           <none>

kubectl get pods -n kube-system
NAME                                 READY   STATUS    RESTARTS   AGE
coredns-6d56c8448f-844s9             1/1     Running   2          3h22m
coredns-6d56c8448f-hwcnb             1/1     Running   2          3h22m
etcd-k8s-master                      1/1     Running   3          3h22m
kube-apiserver-k8s-master            1/1     Running   0          25m
kube-controller-manager-k8s-master   1/1     Running   5          3h22m
kube-proxy-lx2ww                     1/1     Running   2          3h22m
kube-proxy-vmxwm                     1/1     Running   3          3h5m
kube-scheduler-k8s-master            1/1     Running   4          3h22m

**Comment by daixiang0** [comment]
@beyondyinjl2 hi, please check out latest codes and follow readme again, there is a fix for this.

**Comment by daixiang0** [comment]
Please try the latest example to confirm this issue exists or not, it works at my env, thanks :)

**Comment by beyondyinjl2** [comment]
ok
